### ISSUE TITLE
Undefined index: password

### ISSUE THREAD

**Issue by penafarhan** [jahondust/model-log#2]
I used ModelLogging inside User, when I did register and login, it showed this error notification.

**Comment by Bakho0707** [comment]
The problem with 'Undefined index: password #2' has been fixed in **version 1.0.2**.
All attributes inside of your model's hidden property  won't be shown, 
if you want to show them just exclude them  from the hidden property.

**Comment by penafarhan** [comment]
Thanks sir, it worked.
